abjad.OrderedDict(
    [
        (
            "alive_during_segment",
            [
                "Score",
                "Global_Context",
                "Global_Skips",
                "Music_Context",
                "Staff_Group",
                "Staff_I",
                "Global_Rests",
                "Percussion_Voice_I",
                "Percussion_Rest_Voice_I",
                "Staff_II",
                "Percussion_Voice_II",
                "Percussion_Rest_Voice_II",
                "Staff_III",
                "Percussion_Voice_III",
                "Percussion_Rest_Voice_III",
                "Staff_IV",
                "Percussion_Voice_IV",
                "Percussion_Rest_Voice_IV",
                "Staff_V",
                "Percussion_Voice_V",
                "Percussion_Rest_Voice_V",
                "Staff_VI",
                "Percussion_Voice_VI",
                "Percussion_Rest_Voice_VI",
                "Staff_VII",
                "Percussion_Voice_VII",
                "Percussion_Rest_Voice_VII",
                "Staff_VIII",
                "Percussion_Voice_VIII",
                "Percussion_Rest_Voice_VIII",
                "Staff_IX",
                "Percussion_Voice_IX",
                "Percussion_Rest_Voice_IX",
                "Staff_X",
                "Percussion_Voice_X",
                "Percussion_Rest_Voice_X",
                "Staff_XI",
                "Percussion_Voice_XI",
                "Percussion_Rest_Voice_XI",
                "Staff_XII",
                "Percussion_Voice_XII",
                "Percussion_Rest_Voice_XII",
                "Staff_XIII",
                "Percussion_Voice_XIII",
                "Percussion_Rest_Voice_XIII",
                "Staff_XIV",
                "Percussion_Voice_XIV",
                "Percussion_Rest_Voice_XIV",
                "Staff_XV",
                "Percussion_Voice_XV",
                "Percussion_Rest_Voice_XV",
                "Staff_XVI",
                "Percussion_Voice_XVI",
                "Percussion_Rest_Voice_XVI",
                "Staff_XVII",
                "Percussion_Voice_XVII",
                "Percussion_Rest_Voice_XVII",
                "Staff_XVIII",
                "Percussion_Voice_XVIII",
                "Percussion_Rest_Voice_XVIII",
                "Staff_XIX",
                "Percussion_Voice_XIX",
                "Percussion_Rest_Voice_XIX",
                "Staff_XX",
                "Percussion_Voice_XX",
                "Percussion_Rest_Voice_XX",
                "Staff_XXI",
                "Percussion_Voice_XXI",
                "Percussion_Rest_Voice_XXI",
                "Staff_XXII",
                "Percussion_Voice_XXII",
                "Percussion_Rest_Voice_XXII",
                "Staff_XXIII",
                "Percussion_Voice_XXIII",
                "Percussion_Rest_Voice_XXIII",
                "Staff_XXIV",
                "Percussion_Voice_XXIV",
                "Percussion_Rest_Voice_XXIV",
                "Staff_XXV",
                "Percussion_Voice_XXV",
                "Percussion_Rest_Voice_XXV",
                "Staff_XXVI",
                "Percussion_Voice_XXVI",
                "Percussion_Rest_Voice_XXVI",
                "Staff_XXVII",
                "Percussion_Voice_XXVII",
                "Percussion_Rest_Voice_XXVII",
                "Staff_XXVIII",
                "Percussion_Voice_XXVIII",
                "Percussion_Rest_Voice_XXVIII",
                "Staff_XXIX",
                "Percussion_Voice_XXIX",
                "Percussion_Rest_Voice_XXIX",
                "Staff_XXX",
                "Percussion_Voice_XXX",
                "Percussion_Rest_Voice_XXX",
                "Staff_XXXI",
                "Percussion_Voice_XXXI",
                "Percussion_Rest_Voice_XXXI",
                "Staff_XXXII",
                "Percussion_Voice_XXXII",
                "Percussion_Rest_Voice_XXXII",
                "Staff_XXXIII",
                "Percussion_Voice_XXXIII",
                "Percussion_Rest_Voice_XXXIII",
                "Staff_XXXIV",
                "Percussion_Voice_XXXIV",
                "Percussion_Rest_Voice_XXXIV",
                "Staff_XXXV",
                "Percussion_Voice_XXXV",
                "Percussion_Rest_Voice_XXXV",
                "Staff_XXXVI",
                "Percussion_Voice_XXXVI",
                "Percussion_Rest_Voice_XXXVI",
                "Staff_XXXVII",
                "Percussion_Voice_XXXVII",
                "Percussion_Rest_Voice_XXXVII",
                "Staff_XXXVIII",
                "Percussion_Voice_XXXVIII",
                "Percussion_Rest_Voice_XXXVIII",
                "Staff_XXXIX",
                "Percussion_Voice_XXXIX",
                "Percussion_Rest_Voice_XXXIX",
                "Staff_XL",
                "Percussion_Voice_XL",
                "Percussion_Rest_Voice_XL",
                "Staff_XLI",
                "Percussion_Voice_XLI",
                "Percussion_Rest_Voice_XLI",
                "Staff_XLII",
                "Percussion_Voice_XLII",
                "Percussion_Rest_Voice_XLII",
                "Staff_XLIII",
                "Percussion_Voice_XLIII",
                "Percussion_Rest_Voice_XLIII",
                "Staff_XLIV",
                "Percussion_Voice_XLIV",
                "Percussion_Rest_Voice_XLIV",
                "Staff_XLV",
                "Percussion_Voice_XLV",
                "Percussion_Rest_Voice_XLV",
                "Staff_XLVI",
                "Percussion_Voice_XLVI",
                "Percussion_Rest_Voice_XLVI",
                "Staff_XLVII",
                "Percussion_Voice_XLVII",
                "Percussion_Rest_Voice_XLVII",
                "Staff_XLVIII",
                "Percussion_Voice_XLVIII",
                "Percussion_Rest_Voice_XLVIII",
                "Staff_XLIX",
                "Percussion_Voice_XLIX",
                "Percussion_Rest_Voice_XLIX",
                "Staff_L",
                "Percussion_Voice_L",
                "Percussion_Rest_Voice_L",
                "Staff_LI",
                "Percussion_Voice_LI",
                "Percussion_Rest_Voice_LI",
                "Staff_LII",
                "Percussion_Voice_LII",
                "Percussion_Rest_Voice_LII",
                "Staff_LIII",
                "Percussion_Voice_LIII",
                "Percussion_Rest_Voice_LIII",
                "Staff_LIV",
                "Percussion_Voice_LIV",
                "Percussion_Rest_Voice_LIV",
                "Staff_LV",
                "Percussion_Voice_LV",
                "Percussion_Rest_Voice_LV",
                "Staff_LVI",
                "Percussion_Voice_LVI",
                "Percussion_Rest_Voice_LVI",
                "Staff_LVII",
                "Percussion_Voice_LVII",
                "Percussion_Rest_Voice_LVII",
                "Staff_LVIII",
                "Percussion_Voice_LVIII",
                "Percussion_Rest_Voice_LVIII",
                "Staff_LIX",
                "Percussion_Voice_LIX",
                "Percussion_Rest_Voice_LIX",
                "Staff_LX",
                "Percussion_Voice_LX",
                "Percussion_Rest_Voice_LX",
                "Staff_LXI",
                "Percussion_Voice_LXI",
                "Percussion_Rest_Voice_LXI",
                "Staff_LXII",
                "Percussion_Voice_LXII",
                "Percussion_Rest_Voice_LXII",
                "Staff_LXIII",
                "Percussion_Voice_LXIII",
                "Percussion_Rest_Voice_LXIII",
                "Staff_LXIV",
                "Percussion_Voice_LXIV",
                "Percussion_Rest_Voice_LXIV",
            ],
        ),
        (
            "container_to_part_assignment",
            abjad.OrderedDict(
                [
                    (
                        "d_Percussion_Voice_III_a",
                        (
                            baca.PartAssignment("Percussion", 3),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_II_a",
                        (
                            baca.PartAssignment("Percussion", 2),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_IV_a",
                        (
                            baca.PartAssignment("Percussion", 4),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_IX_a",
                        (
                            baca.PartAssignment("Percussion", 9),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_I_a",
                        (
                            baca.PartAssignment("Percussion", 1),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_LIII_a",
                        (
                            baca.PartAssignment("Percussion", 53),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_LII_a",
                        (
                            baca.PartAssignment("Percussion", 52),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_LIV_a",
                        (
                            baca.PartAssignment("Percussion", 54),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_LIX_a",
                        (
                            baca.PartAssignment("Percussion", 59),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_LI_a",
                        (
                            baca.PartAssignment("Percussion", 51),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_LVIII_a",
                        (
                            baca.PartAssignment("Percussion", 58),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_LVII_a",
                        (
                            baca.PartAssignment("Percussion", 57),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_LVI_a",
                        (
                            baca.PartAssignment("Percussion", 56),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_LV_a",
                        (
                            baca.PartAssignment("Percussion", 55),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_LXIII_a",
                        (
                            baca.PartAssignment("Percussion", 63),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_LXII_a",
                        (
                            baca.PartAssignment("Percussion", 62),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_LXIV_a",
                        (
                            baca.PartAssignment("Percussion", 64),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_LXI_a",
                        (
                            baca.PartAssignment("Percussion", 61),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_LX_a",
                        (
                            baca.PartAssignment("Percussion", 60),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_L_a",
                        (
                            baca.PartAssignment("Percussion", 50),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_VIII_a",
                        (
                            baca.PartAssignment("Percussion", 8),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_VII_a",
                        (
                            baca.PartAssignment("Percussion", 7),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_VI_a",
                        (
                            baca.PartAssignment("Percussion", 6),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_V_a",
                        (
                            baca.PartAssignment("Percussion", 5),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XIII_a",
                        (
                            baca.PartAssignment("Percussion", 13),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XII_a",
                        (
                            baca.PartAssignment("Percussion", 12),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XIV_a",
                        (
                            baca.PartAssignment("Percussion", 14),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XIX_a",
                        (
                            baca.PartAssignment("Percussion", 19),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XI_a",
                        (
                            baca.PartAssignment("Percussion", 11),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XLIII_a",
                        (
                            baca.PartAssignment("Percussion", 43),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XLII_a",
                        (
                            baca.PartAssignment("Percussion", 42),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XLIV_a",
                        (
                            baca.PartAssignment("Percussion", 44),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XLIX_a",
                        (
                            baca.PartAssignment("Percussion", 49),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XLI_a",
                        (
                            baca.PartAssignment("Percussion", 41),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XLVIII_a",
                        (
                            baca.PartAssignment("Percussion", 48),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XLVII_a",
                        (
                            baca.PartAssignment("Percussion", 47),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XLVI_a",
                        (
                            baca.PartAssignment("Percussion", 46),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XLV_a",
                        (
                            baca.PartAssignment("Percussion", 45),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XL_a",
                        (
                            baca.PartAssignment("Percussion", 40),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XVIII_a",
                        (
                            baca.PartAssignment("Percussion", 18),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XVII_a",
                        (
                            baca.PartAssignment("Percussion", 17),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XVI_a",
                        (
                            baca.PartAssignment("Percussion", 16),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XV_a",
                        (
                            baca.PartAssignment("Percussion", 15),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXIII_a",
                        (
                            baca.PartAssignment("Percussion", 23),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXII_a",
                        (
                            baca.PartAssignment("Percussion", 22),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXIV_a",
                        (
                            baca.PartAssignment("Percussion", 24),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXIX_a",
                        (
                            baca.PartAssignment("Percussion", 29),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXI_a",
                        (
                            baca.PartAssignment("Percussion", 21),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXVIII_a",
                        (
                            baca.PartAssignment("Percussion", 28),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXVII_a",
                        (
                            baca.PartAssignment("Percussion", 27),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXVI_a",
                        (
                            baca.PartAssignment("Percussion", 26),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXV_a",
                        (
                            baca.PartAssignment("Percussion", 25),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXXIII_a",
                        (
                            baca.PartAssignment("Percussion", 33),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXXII_a",
                        (
                            baca.PartAssignment("Percussion", 32),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXXIV_a",
                        (
                            baca.PartAssignment("Percussion", 34),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXXIX_a",
                        (
                            baca.PartAssignment("Percussion", 39),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXXI_a",
                        (
                            baca.PartAssignment("Percussion", 31),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXXVIII_a",
                        (
                            baca.PartAssignment("Percussion", 38),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXXVII_a",
                        (
                            baca.PartAssignment("Percussion", 37),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXXVI_a",
                        (
                            baca.PartAssignment("Percussion", 36),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXXV_a",
                        (
                            baca.PartAssignment("Percussion", 35),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XXX_a",
                        (
                            baca.PartAssignment("Percussion", 30),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_XX_a",
                        (
                            baca.PartAssignment("Percussion", 20),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                    (
                        "d_Percussion_Voice_X_a",
                        (
                            baca.PartAssignment("Percussion", 10),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                            ),
                        ),
                    ),
                ]
            ),
        ),
        (
            "persistent_indicators",
            abjad.OrderedDict(
                [
                    (
                        "Score",
                        [
                            baca.Momento(
                                context="Global_Skips",
                                manifest="metronome_marks",
                                value="38-42",
                            ),
                            baca.Momento(
                                context="Global_Skips",
                                prototype="abjad.TimeSignature",
                                value="2/4",
                            ),
                        ],
                    ),
                    (
                        "Staff_I",
                        [
                            baca.Momento(
                                context="Percussion_Voice_I",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="1",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_I",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_I",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_II",
                        [
                            baca.Momento(
                                context="Percussion_Voice_II",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="2",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_II",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_II",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_III",
                        [
                            baca.Momento(
                                context="Percussion_Voice_III",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="3",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_III",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_III",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_IV",
                        [
                            baca.Momento(
                                context="Percussion_Voice_IV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="4",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_IV",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_IV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_IX",
                        [
                            baca.Momento(
                                context="Percussion_Voice_IX",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="9",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_IX",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_IX",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_L",
                        [
                            baca.Momento(
                                context="Percussion_Voice_L",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="50",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_L",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_L",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_LI",
                        [
                            baca.Momento(
                                context="Percussion_Voice_LI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="51",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LI",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_LII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_LII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="52",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_LIII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_LIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="53",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LIII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_LIV",
                        [
                            baca.Momento(
                                context="Percussion_Voice_LIV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="54",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LIV",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LIV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_LIX",
                        [
                            baca.Momento(
                                context="Percussion_Voice_LIX",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="59",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LIX",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LIX",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_LV",
                        [
                            baca.Momento(
                                context="Percussion_Voice_LV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="55",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LV",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_LVI",
                        [
                            baca.Momento(
                                context="Percussion_Voice_LVI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="56",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LVI",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LVI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_LVII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_LVII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="57",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LVII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LVII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_LVIII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_LVIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="58",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LVIII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LVIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_LX",
                        [
                            baca.Momento(
                                context="Percussion_Voice_LX",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="60",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LX",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LX",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_LXI",
                        [
                            baca.Momento(
                                context="Percussion_Voice_LXI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="61",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LXI",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LXI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_LXII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_LXII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="62",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LXII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LXII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_LXIII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_LXIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="63",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LXIII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LXIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_LXIV",
                        [
                            baca.Momento(
                                context="Percussion_Voice_LXIV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="64",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LXIV",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_LXIV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_V",
                        [
                            baca.Momento(
                                context="Percussion_Voice_V",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="5",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_V",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_V",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_VI",
                        [
                            baca.Momento(
                                context="Percussion_Voice_VI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="6",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_VI",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_VI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_VII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_VII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="7",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_VII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_VII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_VIII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_VIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="8",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_VIII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_VIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_X",
                        [
                            baca.Momento(
                                context="Percussion_Voice_X",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="10",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_X",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_X",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XI",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="11",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XI",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="12",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XIII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="13",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XIII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XIV",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XIV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="14",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XIV",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XIV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XIX",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XIX",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="19",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XIX",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XIX",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XL",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XL",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="40",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XL",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XL",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XLI",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XLI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="41",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLI",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XLII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XLII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="42",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XLIII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XLIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="43",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLIII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XLIV",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XLIV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="44",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLIV",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLIV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XLIX",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XLIX",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="49",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLIX",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLIX",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XLV",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XLV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="45",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLV",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XLVI",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XLVI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="46",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLVI",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLVI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XLVII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XLVII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="47",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLVII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLVII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XLVIII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XLVIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="48",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLVIII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XLVIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XV",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="15",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XV",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XVI",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XVI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="16",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XVI",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XVI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XVII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XVII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="17",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XVII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XVII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XVIII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XVIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="18",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XVIII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XVIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XX",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XX",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="20",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XX",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XX",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXI",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="21",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXI",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="22",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXIII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="23",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXIII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXIV",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXIV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="24",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXIV",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXIV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXIX",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXIX",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="29",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXIX",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXIX",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXV",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="25",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXV",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXVI",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXVI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="26",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXVI",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXVI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXVII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXVII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="27",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXVII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXVII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXVIII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXVIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="28",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXVIII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXVIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXX",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXX",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="30",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXX",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXX",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXXI",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXXI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="31",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXI",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXXII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXXII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="32",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXXIII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXXIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="33",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXIII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXXIV",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXXIV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="34",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXIV",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXIV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXXIX",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXXIX",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="39",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXIX",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXIX",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXXV",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXXV",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="35",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXV",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXV",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXXVI",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXXVI",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="36",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXVI",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXVI",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXXVII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXXVII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="37",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXVII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXVII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                    (
                        "Staff_XXXVIII",
                        [
                            baca.Momento(
                                context="Percussion_Voice_XXXVIII",
                                edition=abjad.Tag("-PARTS"),
                                manifest="margin_markups",
                                value="38",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXVIII",
                                manifest="instruments",
                                value="Percussion",
                            ),
                            baca.Momento(
                                context="Percussion_Voice_XXXVIII",
                                prototype="abjad.Clef",
                                value="percussion",
                            ),
                        ],
                    ),
                ]
            ),
        ),
    ]
)
