import abjad
import ide


persist = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'Global_Context',
                'Global_Skips',
                'Music_Context',
                'Staff_Group',
                'Staff_I',
                'Global_Rests',
                'Percussion_Voice_I',
                'Percussion_Rest_Voice_I',
                'Staff_II',
                'Percussion_Voice_II',
                'Percussion_Rest_Voice_II',
                'Staff_III',
                'Percussion_Voice_III',
                'Percussion_Rest_Voice_III',
                'Staff_IV',
                'Percussion_Voice_IV',
                'Percussion_Rest_Voice_IV',
                'Staff_V',
                'Percussion_Voice_V',
                'Percussion_Rest_Voice_V',
                'Staff_VI',
                'Percussion_Voice_VI',
                'Percussion_Rest_Voice_VI',
                'Staff_VII',
                'Percussion_Voice_VII',
                'Percussion_Rest_Voice_VII',
                'Staff_VIII',
                'Percussion_Voice_VIII',
                'Percussion_Rest_Voice_VIII',
                'Staff_IX',
                'Percussion_Voice_IX',
                'Percussion_Rest_Voice_IX',
                'Staff_X',
                'Percussion_Voice_X',
                'Percussion_Rest_Voice_X',
                'Staff_XI',
                'Percussion_Voice_XI',
                'Percussion_Rest_Voice_XI',
                'Staff_XII',
                'Percussion_Voice_XII',
                'Percussion_Rest_Voice_XII',
                'Staff_XIII',
                'Percussion_Voice_XIII',
                'Percussion_Rest_Voice_XIII',
                'Staff_XIV',
                'Percussion_Voice_XIV',
                'Percussion_Rest_Voice_XIV',
                'Staff_XV',
                'Percussion_Voice_XV',
                'Percussion_Rest_Voice_XV',
                'Staff_XVI',
                'Percussion_Voice_XVI',
                'Percussion_Rest_Voice_XVI',
                'Staff_XVII',
                'Percussion_Voice_XVII',
                'Percussion_Rest_Voice_XVII',
                'Staff_XVIII',
                'Percussion_Voice_XVIII',
                'Percussion_Rest_Voice_XVIII',
                'Staff_XIX',
                'Percussion_Voice_XIX',
                'Percussion_Rest_Voice_XIX',
                'Staff_XX',
                'Percussion_Voice_XX',
                'Percussion_Rest_Voice_XX',
                'Staff_XXI',
                'Percussion_Voice_XXI',
                'Percussion_Rest_Voice_XXI',
                'Staff_XXII',
                'Percussion_Voice_XXII',
                'Percussion_Rest_Voice_XXII',
                'Staff_XXIII',
                'Percussion_Voice_XXIII',
                'Percussion_Rest_Voice_XXIII',
                'Staff_XXIV',
                'Percussion_Voice_XXIV',
                'Percussion_Rest_Voice_XXIV',
                'Staff_XXV',
                'Percussion_Voice_XXV',
                'Percussion_Rest_Voice_XXV',
                'Staff_XXVI',
                'Percussion_Voice_XXVI',
                'Percussion_Rest_Voice_XXVI',
                'Staff_XXVII',
                'Percussion_Voice_XXVII',
                'Percussion_Rest_Voice_XXVII',
                'Staff_XXVIII',
                'Percussion_Voice_XXVIII',
                'Percussion_Rest_Voice_XXVIII',
                'Staff_XXIX',
                'Percussion_Voice_XXIX',
                'Percussion_Rest_Voice_XXIX',
                'Staff_XXX',
                'Percussion_Voice_XXX',
                'Percussion_Rest_Voice_XXX',
                'Staff_XXXI',
                'Percussion_Voice_XXXI',
                'Percussion_Rest_Voice_XXXI',
                'Staff_XXXII',
                'Percussion_Voice_XXXII',
                'Percussion_Rest_Voice_XXXII',
                'Staff_XXXIII',
                'Percussion_Voice_XXXIII',
                'Percussion_Rest_Voice_XXXIII',
                'Staff_XXXIV',
                'Percussion_Voice_XXXIV',
                'Percussion_Rest_Voice_XXXIV',
                'Staff_XXXV',
                'Percussion_Voice_XXXV',
                'Percussion_Rest_Voice_XXXV',
                'Staff_XXXVI',
                'Percussion_Voice_XXXVI',
                'Percussion_Rest_Voice_XXXVI',
                'Staff_XXXVII',
                'Percussion_Voice_XXXVII',
                'Percussion_Rest_Voice_XXXVII',
                'Staff_XXXVIII',
                'Percussion_Voice_XXXVIII',
                'Percussion_Rest_Voice_XXXVIII',
                'Staff_XXXIX',
                'Percussion_Voice_XXXIX',
                'Percussion_Rest_Voice_XXXIX',
                'Staff_XL',
                'Percussion_Voice_XL',
                'Percussion_Rest_Voice_XL',
                'Staff_XLI',
                'Percussion_Voice_XLI',
                'Percussion_Rest_Voice_XLI',
                'Staff_XLII',
                'Percussion_Voice_XLII',
                'Percussion_Rest_Voice_XLII',
                'Staff_XLIII',
                'Percussion_Voice_XLIII',
                'Percussion_Rest_Voice_XLIII',
                'Staff_XLIV',
                'Percussion_Voice_XLIV',
                'Percussion_Rest_Voice_XLIV',
                'Staff_XLV',
                'Percussion_Voice_XLV',
                'Percussion_Rest_Voice_XLV',
                'Staff_XLVI',
                'Percussion_Voice_XLVI',
                'Percussion_Rest_Voice_XLVI',
                'Staff_XLVII',
                'Percussion_Voice_XLVII',
                'Percussion_Rest_Voice_XLVII',
                'Staff_XLVIII',
                'Percussion_Voice_XLVIII',
                'Percussion_Rest_Voice_XLVIII',
                'Staff_XLIX',
                'Percussion_Voice_XLIX',
                'Percussion_Rest_Voice_XLIX',
                'Staff_L',
                'Percussion_Voice_L',
                'Percussion_Rest_Voice_L',
                'Staff_LI',
                'Percussion_Voice_LI',
                'Percussion_Rest_Voice_LI',
                'Staff_LII',
                'Percussion_Voice_LII',
                'Percussion_Rest_Voice_LII',
                'Staff_LIII',
                'Percussion_Voice_LIII',
                'Percussion_Rest_Voice_LIII',
                'Staff_LIV',
                'Percussion_Voice_LIV',
                'Percussion_Rest_Voice_LIV',
                'Staff_LV',
                'Percussion_Voice_LV',
                'Percussion_Rest_Voice_LV',
                'Staff_LVI',
                'Percussion_Voice_LVI',
                'Percussion_Rest_Voice_LVI',
                'Staff_LVII',
                'Percussion_Voice_LVII',
                'Percussion_Rest_Voice_LVII',
                'Staff_LVIII',
                'Percussion_Voice_LVIII',
                'Percussion_Rest_Voice_LVIII',
                'Staff_LIX',
                'Percussion_Voice_LIX',
                'Percussion_Rest_Voice_LIX',
                'Staff_LX',
                'Percussion_Voice_LX',
                'Percussion_Rest_Voice_LX',
                'Staff_LXI',
                'Percussion_Voice_LXI',
                'Percussion_Rest_Voice_LXI',
                'Staff_LXII',
                'Percussion_Voice_LXII',
                'Percussion_Rest_Voice_LXII',
                'Staff_LXIII',
                'Percussion_Voice_LXIII',
                'Percussion_Rest_Voice_LXIII',
                'Staff_LXIV',
                'Percussion_Voice_LXIV',
                'Percussion_Rest_Voice_LXIV',
                ],
            ),
        (
            'container_to_part_assignment',
            abjad.OrderedDict(
                [
                    (
                        'N_Percussion_Voice_III_a',
                        (
                            ide.PartAssignment('Percussion', 3),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_II_a',
                        (
                            ide.PartAssignment('Percussion', 2),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_IV_a',
                        (
                            ide.PartAssignment('Percussion', 4),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_IX_a',
                        (
                            ide.PartAssignment('Percussion', 9),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_I_a',
                        (
                            ide.PartAssignment('Percussion', 1),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_LIII_a',
                        (
                            ide.PartAssignment('Percussion', 53),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_LII_a',
                        (
                            ide.PartAssignment('Percussion', 52),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_LIV_a',
                        (
                            ide.PartAssignment('Percussion', 54),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_LIX_a',
                        (
                            ide.PartAssignment('Percussion', 59),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_LI_a',
                        (
                            ide.PartAssignment('Percussion', 51),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_LVIII_a',
                        (
                            ide.PartAssignment('Percussion', 58),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_LVII_a',
                        (
                            ide.PartAssignment('Percussion', 57),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_LVI_a',
                        (
                            ide.PartAssignment('Percussion', 56),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_LV_a',
                        (
                            ide.PartAssignment('Percussion', 55),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_LXIII_a',
                        (
                            ide.PartAssignment('Percussion', 63),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_LXII_a',
                        (
                            ide.PartAssignment('Percussion', 62),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_LXIV_a',
                        (
                            ide.PartAssignment('Percussion', 64),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_LXI_a',
                        (
                            ide.PartAssignment('Percussion', 61),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_LX_a',
                        (
                            ide.PartAssignment('Percussion', 60),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_L_a',
                        (
                            ide.PartAssignment('Percussion', 50),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_VIII_a',
                        (
                            ide.PartAssignment('Percussion', 8),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_VII_a',
                        (
                            ide.PartAssignment('Percussion', 7),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_VI_a',
                        (
                            ide.PartAssignment('Percussion', 6),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_V_a',
                        (
                            ide.PartAssignment('Percussion', 5),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XIII_a',
                        (
                            ide.PartAssignment('Percussion', 13),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XII_a',
                        (
                            ide.PartAssignment('Percussion', 12),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XIV_a',
                        (
                            ide.PartAssignment('Percussion', 14),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XIX_a',
                        (
                            ide.PartAssignment('Percussion', 19),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XI_a',
                        (
                            ide.PartAssignment('Percussion', 11),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XLIII_a',
                        (
                            ide.PartAssignment('Percussion', 43),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XLII_a',
                        (
                            ide.PartAssignment('Percussion', 42),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XLIV_a',
                        (
                            ide.PartAssignment('Percussion', 44),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XLIX_a',
                        (
                            ide.PartAssignment('Percussion', 49),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XLI_a',
                        (
                            ide.PartAssignment('Percussion', 41),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XLVIII_a',
                        (
                            ide.PartAssignment('Percussion', 48),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XLVII_a',
                        (
                            ide.PartAssignment('Percussion', 47),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XLVI_a',
                        (
                            ide.PartAssignment('Percussion', 46),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XLV_a',
                        (
                            ide.PartAssignment('Percussion', 45),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XL_a',
                        (
                            ide.PartAssignment('Percussion', 40),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XVIII_a',
                        (
                            ide.PartAssignment('Percussion', 18),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XVII_a',
                        (
                            ide.PartAssignment('Percussion', 17),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XVI_a',
                        (
                            ide.PartAssignment('Percussion', 16),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XV_a',
                        (
                            ide.PartAssignment('Percussion', 15),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXIII_a',
                        (
                            ide.PartAssignment('Percussion', 23),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXII_a',
                        (
                            ide.PartAssignment('Percussion', 22),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXIV_a',
                        (
                            ide.PartAssignment('Percussion', 24),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXIX_a',
                        (
                            ide.PartAssignment('Percussion', 29),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXI_a',
                        (
                            ide.PartAssignment('Percussion', 21),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXVIII_a',
                        (
                            ide.PartAssignment('Percussion', 28),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXVII_a',
                        (
                            ide.PartAssignment('Percussion', 27),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXVI_a',
                        (
                            ide.PartAssignment('Percussion', 26),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXV_a',
                        (
                            ide.PartAssignment('Percussion', 25),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXXIII_a',
                        (
                            ide.PartAssignment('Percussion', 33),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXXII_a',
                        (
                            ide.PartAssignment('Percussion', 32),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXXIV_a',
                        (
                            ide.PartAssignment('Percussion', 34),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXXIX_a',
                        (
                            ide.PartAssignment('Percussion', 39),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXXI_a',
                        (
                            ide.PartAssignment('Percussion', 31),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXXVIII_a',
                        (
                            ide.PartAssignment('Percussion', 38),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXXVII_a',
                        (
                            ide.PartAssignment('Percussion', 37),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXXVI_a',
                        (
                            ide.PartAssignment('Percussion', 36),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXXV_a',
                        (
                            ide.PartAssignment('Percussion', 35),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XXX_a',
                        (
                            ide.PartAssignment('Percussion', 30),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_XX_a',
                        (
                            ide.PartAssignment('Percussion', 20),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    (
                        'N_Percussion_Voice_X_a',
                        (
                            ide.PartAssignment('Percussion', 10),
                            abjad.Timespan(
                                start_offset=abjad.Offset((0, 1)),
                                stop_offset=abjad.Offset((8, 1)),
                                ),
                            ),
                        ),
                    ]
                ),
            ),
        (
            'persistent_indicators',
            abjad.OrderedDict(
                [
                    (
                        'Score',
                        [
                            ide.Momento(
                                context='Global_Skips',
                                manifest='metronome_marks',
                                value='38-42',
                                ),
                            ide.Momento(
                                context='Global_Skips',
                                prototype='abjad.TimeSignature',
                                value='2/4',
                                ),
                            ],
                        ),
                    (
                        'Staff_I',
                        [
                            ide.Momento(
                                context='Percussion_Voice_I',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='1',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_I',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_I',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_II',
                        [
                            ide.Momento(
                                context='Percussion_Voice_II',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='2',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_II',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_II',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_III',
                        [
                            ide.Momento(
                                context='Percussion_Voice_III',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='3',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_III',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_III',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_IV',
                        [
                            ide.Momento(
                                context='Percussion_Voice_IV',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='4',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_IV',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_IV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_IX',
                        [
                            ide.Momento(
                                context='Percussion_Voice_IX',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='9',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_IX',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_IX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_L',
                        [
                            ide.Momento(
                                context='Percussion_Voice_L',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='50',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_L',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_L',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_LI',
                        [
                            ide.Momento(
                                context='Percussion_Voice_LI',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='51',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LI',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_LII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_LII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='52',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_LIII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_LIII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='53',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LIII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_LIV',
                        [
                            ide.Momento(
                                context='Percussion_Voice_LIV',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='54',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LIV',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_LIX',
                        [
                            ide.Momento(
                                context='Percussion_Voice_LIX',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='59',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LIX',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_LV',
                        [
                            ide.Momento(
                                context='Percussion_Voice_LV',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='55',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LV',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_LVI',
                        [
                            ide.Momento(
                                context='Percussion_Voice_LVI',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='56',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LVI',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_LVII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_LVII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='57',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LVII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_LVIII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_LVIII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='58',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LVIII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_LX',
                        [
                            ide.Momento(
                                context='Percussion_Voice_LX',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='60',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LX',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_LXI',
                        [
                            ide.Momento(
                                context='Percussion_Voice_LXI',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='61',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LXI',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LXI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_LXII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_LXII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='62',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LXII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LXII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_LXIII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_LXIII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='63',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LXIII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LXIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_LXIV',
                        [
                            ide.Momento(
                                context='Percussion_Voice_LXIV',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='64',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LXIV',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_LXIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_V',
                        [
                            ide.Momento(
                                context='Percussion_Voice_V',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='5',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_V',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_V',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_VI',
                        [
                            ide.Momento(
                                context='Percussion_Voice_VI',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='6',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_VI',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_VI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_VII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_VII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='7',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_VII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_VII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_VIII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_VIII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='8',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_VIII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_VIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_X',
                        [
                            ide.Momento(
                                context='Percussion_Voice_X',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='10',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_X',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_X',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XI',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XI',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='11',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XI',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='12',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XIII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XIII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='13',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XIII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XIV',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XIV',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='14',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XIV',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XIX',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XIX',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='19',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XIX',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XL',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XL',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='40',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XL',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XL',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XLI',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XLI',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='41',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLI',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XLII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XLII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='42',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XLIII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XLIII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='43',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLIII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XLIV',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XLIV',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='44',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLIV',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XLIX',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XLIX',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='49',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLIX',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XLV',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XLV',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='45',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLV',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XLVI',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XLVI',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='46',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLVI',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XLVII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XLVII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='47',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLVII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XLVIII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XLVIII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='48',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLVIII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XLVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XV',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XV',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='15',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XV',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XVI',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XVI',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='16',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XVI',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XVII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XVII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='17',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XVII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XVIII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XVIII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='18',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XVIII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XX',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XX',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='20',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XX',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXI',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXI',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='21',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXI',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='22',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXIII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXIII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='23',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXIII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXIV',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXIV',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='24',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXIV',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXIX',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXIX',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='29',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXIX',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXV',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXV',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='25',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXV',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXVI',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXVI',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='26',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXVI',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXVII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXVII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='27',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXVII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXVIII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXVIII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='28',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXVIII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXX',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXX',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='30',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXX',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXXI',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXXI',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='31',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXI',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXXII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXXII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='32',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXXIII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXXIII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='33',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXIII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXXIV',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXXIV',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='34',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXIV',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXXIX',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXXIX',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='39',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXIX',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXXV',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXXV',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='35',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXV',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXXVI',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXXVI',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='36',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXVI',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXXVII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXXVII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='37',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXVII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    (
                        'Staff_XXXVIII',
                        [
                            ide.Momento(
                                context='Percussion_Voice_XXXVIII',
                                edition=abjad.Tag('-PARTS'),
                                manifest='margin_markups',
                                value='38',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXVIII',
                                manifest='instruments',
                                value='Percussion',
                                ),
                            ide.Momento(
                                context='Percussion_Voice_XXXVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            ],
                        ),
                    ]
                ),
            ),
        ]
    )
