import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'GlobalContext',
                'GlobalSkips',
                'MusicContext',
                'StaffGroup',
                'StaffI',
                'PercussionVoiceI',
                'StaffII',
                'PercussionVoiceII',
                'StaffIII',
                'PercussionVoiceIII',
                'StaffIV',
                'PercussionVoiceIV',
                'StaffV',
                'PercussionVoiceV',
                'StaffVI',
                'PercussionVoiceVI',
                'StaffVII',
                'PercussionVoiceVII',
                'StaffVIII',
                'PercussionVoiceVIII',
                'StaffIX',
                'PercussionVoiceIX',
                'StaffX',
                'PercussionVoiceX',
                'StaffXI',
                'PercussionVoiceXI',
                'StaffXII',
                'PercussionVoiceXII',
                'StaffXIII',
                'PercussionVoiceXIII',
                'StaffXIV',
                'PercussionVoiceXIV',
                'StaffXV',
                'PercussionVoiceXV',
                'StaffXVI',
                'PercussionVoiceXVI',
                'StaffXVII',
                'PercussionVoiceXVII',
                'StaffXVIII',
                'PercussionVoiceXVIII',
                'StaffXIX',
                'PercussionVoiceXIX',
                'StaffXX',
                'PercussionVoiceXX',
                'StaffXXI',
                'PercussionVoiceXXI',
                'StaffXXII',
                'PercussionVoiceXXII',
                'StaffXXIII',
                'PercussionVoiceXXIII',
                'StaffXXIV',
                'PercussionVoiceXXIV',
                'StaffXXV',
                'PercussionVoiceXXV',
                'StaffXXVI',
                'PercussionVoiceXXVI',
                'StaffXXVII',
                'PercussionVoiceXXVII',
                'StaffXXVIII',
                'PercussionVoiceXXVIII',
                'StaffXXIX',
                'PercussionVoiceXXIX',
                'StaffXXX',
                'PercussionVoiceXXX',
                'StaffXXXI',
                'PercussionVoiceXXXI',
                'StaffXXXII',
                'PercussionVoiceXXXII',
                'StaffXXXIII',
                'PercussionVoiceXXXIII',
                'StaffXXXIV',
                'PercussionVoiceXXXIV',
                'StaffXXXV',
                'PercussionVoiceXXXV',
                'StaffXXXVI',
                'PercussionVoiceXXXVI',
                'StaffXXXVII',
                'PercussionVoiceXXXVII',
                'StaffXXXVIII',
                'PercussionVoiceXXXVIII',
                'StaffXXXIX',
                'PercussionVoiceXXXIX',
                'StaffXL',
                'PercussionVoiceXL',
                'StaffXLI',
                'PercussionVoiceXLI',
                'StaffXLII',
                'PercussionVoiceXLII',
                'StaffXLIII',
                'PercussionVoiceXLIII',
                'StaffXLIV',
                'PercussionVoiceXLIV',
                'StaffXLV',
                'PercussionVoiceXLV',
                'StaffXLVI',
                'PercussionVoiceXLVI',
                'StaffXLVII',
                'PercussionVoiceXLVII',
                'StaffXLVIII',
                'PercussionVoiceXLVIII',
                'StaffXLIX',
                'PercussionVoiceXLIX',
                'StaffL',
                'PercussionVoiceL',
                'StaffLI',
                'PercussionVoiceLI',
                'StaffLII',
                'PercussionVoiceLII',
                'StaffLIII',
                'PercussionVoiceLIII',
                'StaffLIV',
                'PercussionVoiceLIV',
                'StaffLV',
                'PercussionVoiceLV',
                'StaffLVI',
                'PercussionVoiceLVI',
                'StaffLVII',
                'PercussionVoiceLVII',
                'StaffLVIII',
                'PercussionVoiceLVIII',
                'StaffLIX',
                'PercussionVoiceLIX',
                'StaffLX',
                'PercussionVoiceLX',
                'StaffLXI',
                'PercussionVoiceLXI',
                'StaffLXII',
                'PercussionVoiceLXII',
                'StaffLXIII',
                'PercussionVoiceLXIII',
                'StaffLXIV',
                'PercussionVoiceLXIV',
                ],
            ),
        ('duration', "0'24''"),
        ('first_measure_number', 129),
        ('last_measure_number', 144),
        (
            'persistent_indicators',
            abjad.OrderedDict(
                [
                    (
                        'Score',
                        [
                            abjad.Momento(
                                context='GlobalSkips',
                                prototype='abjad.MetronomeMark',
                                value='38-42',
                                ),
                            abjad.Momento(
                                context='GlobalSkips',
                                prototype='abjad.TimeSignature',
                                value='2/4',
                                ),
                            ],
                        ),
                    (
                        'StaffI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='1',
                                ),
                            ],
                        ),
                    (
                        'StaffII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='2',
                                ),
                            ],
                        ),
                    (
                        'StaffIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='3',
                                ),
                            ],
                        ),
                    (
                        'StaffIV',
                        [
                            abjad.Momento(
                                context='PercussionVoiceIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceIV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceIV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='4',
                                ),
                            ],
                        ),
                    (
                        'StaffIX',
                        [
                            abjad.Momento(
                                context='PercussionVoiceIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceIX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceIX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='9',
                                ),
                            ],
                        ),
                    (
                        'StaffL',
                        [
                            abjad.Momento(
                                context='PercussionVoiceL',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceL',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceL',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='50',
                                ),
                            ],
                        ),
                    (
                        'StaffLI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceLI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='51',
                                ),
                            ],
                        ),
                    (
                        'StaffLII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceLII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='52',
                                ),
                            ],
                        ),
                    (
                        'StaffLIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceLIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='53',
                                ),
                            ],
                        ),
                    (
                        'StaffLIV',
                        [
                            abjad.Momento(
                                context='PercussionVoiceLIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLIV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLIV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='54',
                                ),
                            ],
                        ),
                    (
                        'StaffLIX',
                        [
                            abjad.Momento(
                                context='PercussionVoiceLIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLIX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLIX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='59',
                                ),
                            ],
                        ),
                    (
                        'StaffLV',
                        [
                            abjad.Momento(
                                context='PercussionVoiceLV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='55',
                                ),
                            ],
                        ),
                    (
                        'StaffLVI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceLVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLVI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLVI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='56',
                                ),
                            ],
                        ),
                    (
                        'StaffLVII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceLVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLVII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLVII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='57',
                                ),
                            ],
                        ),
                    (
                        'StaffLVIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceLVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLVIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLVIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='58',
                                ),
                            ],
                        ),
                    (
                        'StaffLX',
                        [
                            abjad.Momento(
                                context='PercussionVoiceLX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='60',
                                ),
                            ],
                        ),
                    (
                        'StaffLXI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceLXI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLXI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLXI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='61',
                                ),
                            ],
                        ),
                    (
                        'StaffLXII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceLXII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLXII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLXII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='62',
                                ),
                            ],
                        ),
                    (
                        'StaffLXIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceLXIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLXIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLXIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='63',
                                ),
                            ],
                        ),
                    (
                        'StaffLXIV',
                        [
                            abjad.Momento(
                                context='PercussionVoiceLXIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLXIV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceLXIV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='64',
                                ),
                            ],
                        ),
                    (
                        'StaffV',
                        [
                            abjad.Momento(
                                context='PercussionVoiceV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='5',
                                ),
                            ],
                        ),
                    (
                        'StaffVI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceVI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceVI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='6',
                                ),
                            ],
                        ),
                    (
                        'StaffVII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceVII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceVII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='7',
                                ),
                            ],
                        ),
                    (
                        'StaffVIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceVIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceVIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='8',
                                ),
                            ],
                        ),
                    (
                        'StaffX',
                        [
                            abjad.Momento(
                                context='PercussionVoiceX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='10',
                                ),
                            ],
                        ),
                    (
                        'StaffXI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='11',
                                ),
                            ],
                        ),
                    (
                        'StaffXII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='12',
                                ),
                            ],
                        ),
                    (
                        'StaffXIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='13',
                                ),
                            ],
                        ),
                    (
                        'StaffXIV',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXIV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXIV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='14',
                                ),
                            ],
                        ),
                    (
                        'StaffXIX',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXIX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXIX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='19',
                                ),
                            ],
                        ),
                    (
                        'StaffXL',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXL',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXL',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXL',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='40',
                                ),
                            ],
                        ),
                    (
                        'StaffXLI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXLI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='41',
                                ),
                            ],
                        ),
                    (
                        'StaffXLII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXLII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='42',
                                ),
                            ],
                        ),
                    (
                        'StaffXLIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXLIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='43',
                                ),
                            ],
                        ),
                    (
                        'StaffXLIV',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXLIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLIV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLIV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='44',
                                ),
                            ],
                        ),
                    (
                        'StaffXLIX',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXLIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLIX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLIX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='49',
                                ),
                            ],
                        ),
                    (
                        'StaffXLV',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXLV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='45',
                                ),
                            ],
                        ),
                    (
                        'StaffXLVI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXLVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLVI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLVI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='46',
                                ),
                            ],
                        ),
                    (
                        'StaffXLVII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXLVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLVII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLVII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='47',
                                ),
                            ],
                        ),
                    (
                        'StaffXLVIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXLVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLVIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXLVIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='48',
                                ),
                            ],
                        ),
                    (
                        'StaffXV',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='15',
                                ),
                            ],
                        ),
                    (
                        'StaffXVI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXVI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXVI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='16',
                                ),
                            ],
                        ),
                    (
                        'StaffXVII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXVII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXVII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='17',
                                ),
                            ],
                        ),
                    (
                        'StaffXVIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXVIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXVIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='18',
                                ),
                            ],
                        ),
                    (
                        'StaffXX',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='20',
                                ),
                            ],
                        ),
                    (
                        'StaffXXI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='21',
                                ),
                            ],
                        ),
                    (
                        'StaffXXII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='22',
                                ),
                            ],
                        ),
                    (
                        'StaffXXIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='23',
                                ),
                            ],
                        ),
                    (
                        'StaffXXIV',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXIV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXIV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='24',
                                ),
                            ],
                        ),
                    (
                        'StaffXXIX',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXIX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXIX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='29',
                                ),
                            ],
                        ),
                    (
                        'StaffXXV',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='25',
                                ),
                            ],
                        ),
                    (
                        'StaffXXVI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXVI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXVI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='26',
                                ),
                            ],
                        ),
                    (
                        'StaffXXVII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXVII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXVII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='27',
                                ),
                            ],
                        ),
                    (
                        'StaffXXVIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXVIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXVIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='28',
                                ),
                            ],
                        ),
                    (
                        'StaffXXX',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='30',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXXI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='31',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXXII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='32',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXXIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='33',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXIV',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXXIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXIV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXIV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='34',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXIX',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXXIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXIX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXIX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='39',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXV',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXXV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='35',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXVI',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXXVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXVI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXVI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='36',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXVII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXXVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXVII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXVII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='37',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXVIII',
                        [
                            abjad.Momento(
                                context='PercussionVoiceXXXVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXVIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='PercussionVoiceXXXVIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='38',
                                ),
                            ],
                        ),
                    ]
                ),
            ),
        ('segment_name', 'H'),
        ('segment_number', 9),
        (
            'sounds_during_segment',
            abjad.OrderedDict(
                [
                    ('PercussionVoiceI', True),
                    ('PercussionVoiceII', True),
                    ('PercussionVoiceIII', True),
                    ('PercussionVoiceIV', True),
                    ('PercussionVoiceIX', True),
                    ('PercussionVoiceL', False),
                    ('PercussionVoiceLI', False),
                    ('PercussionVoiceLII', False),
                    ('PercussionVoiceLIII', False),
                    ('PercussionVoiceLIV', False),
                    ('PercussionVoiceLIX', False),
                    ('PercussionVoiceLV', False),
                    ('PercussionVoiceLVI', False),
                    ('PercussionVoiceLVII', False),
                    ('PercussionVoiceLVIII', False),
                    ('PercussionVoiceLX', False),
                    ('PercussionVoiceLXI', False),
                    ('PercussionVoiceLXII', False),
                    ('PercussionVoiceLXIII', False),
                    ('PercussionVoiceLXIV', False),
                    ('PercussionVoiceV', True),
                    ('PercussionVoiceVI', True),
                    ('PercussionVoiceVII', True),
                    ('PercussionVoiceVIII', True),
                    ('PercussionVoiceX', True),
                    ('PercussionVoiceXI', True),
                    ('PercussionVoiceXII', True),
                    ('PercussionVoiceXIII', True),
                    ('PercussionVoiceXIV', True),
                    ('PercussionVoiceXIX', False),
                    ('PercussionVoiceXL', True),
                    ('PercussionVoiceXLI', True),
                    ('PercussionVoiceXLII', True),
                    ('PercussionVoiceXLIII', True),
                    ('PercussionVoiceXLIV', True),
                    ('PercussionVoiceXLIX', False),
                    ('PercussionVoiceXLV', True),
                    ('PercussionVoiceXLVI', True),
                    ('PercussionVoiceXLVII', True),
                    ('PercussionVoiceXLVIII', True),
                    ('PercussionVoiceXV', True),
                    ('PercussionVoiceXVI', True),
                    ('PercussionVoiceXVII', False),
                    ('PercussionVoiceXVIII', False),
                    ('PercussionVoiceXX', False),
                    ('PercussionVoiceXXI', False),
                    ('PercussionVoiceXXII', False),
                    ('PercussionVoiceXXIII', False),
                    ('PercussionVoiceXXIV', False),
                    ('PercussionVoiceXXIX', False),
                    ('PercussionVoiceXXV', False),
                    ('PercussionVoiceXXVI', False),
                    ('PercussionVoiceXXVII', False),
                    ('PercussionVoiceXXVIII', False),
                    ('PercussionVoiceXXX', False),
                    ('PercussionVoiceXXXI', False),
                    ('PercussionVoiceXXXII', False),
                    ('PercussionVoiceXXXIII', True),
                    ('PercussionVoiceXXXIV', True),
                    ('PercussionVoiceXXXIX', True),
                    ('PercussionVoiceXXXV', True),
                    ('PercussionVoiceXXXVI', True),
                    ('PercussionVoiceXXXVII', True),
                    ('PercussionVoiceXXXVIII', True),
                    ]
                ),
            ),
        ('start_clock_time', "3'12''"),
        ('stop_clock_time', "3'36''"),
        (
            'time_signatures',
            [
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                ],
            ),
        ]
    )
