\version "2.13.11"
\include "english.ly"
\include "/Users/trevorbaca/scores/recursif/_share/ly/parts-layout.ly"


\new Score {
    \new RhythmicStaff <<
        \include "/Users/trevorbaca/scores/recursif/_share/ly/parts-line-breaking.ly"
        {
            \set RhythmicStaff.instrumentName = \markup { 1 \hspace #4 }
            \set RhythmicStaff.shortInstrumentName = \markup { 1 \hspace #4 }
            \time 2/4
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
            b'2
        }
    >>
}

\paper {
    oddFooterMarkup = \markup \fill-line { \italic {
        "Bača / Poème récursif, verse I / 1 of 64" } }
}
