import abjad


metadata = abjad.OrderedDict(
    [
        (
            'alive_during_segment',
            [
                'Score',
                'GlobalContext',
                'GlobalSkips',
                'MusicContext',
                'StaffGroup',
                'StaffI',
                'VoiceI',
                'StaffII',
                'VoiceII',
                'StaffIII',
                'VoiceIII',
                'StaffIV',
                'VoiceIV',
                'StaffV',
                'VoiceV',
                'StaffVI',
                'VoiceVI',
                'StaffVII',
                'VoiceVII',
                'StaffVIII',
                'VoiceVIII',
                'StaffIX',
                'VoiceIX',
                'StaffX',
                'VoiceX',
                'StaffXI',
                'VoiceXI',
                'StaffXII',
                'VoiceXII',
                'StaffXIII',
                'VoiceXIII',
                'StaffXIV',
                'VoiceXIV',
                'StaffXV',
                'VoiceXV',
                'StaffXVI',
                'VoiceXVI',
                'StaffXVII',
                'VoiceXVII',
                'StaffXVIII',
                'VoiceXVIII',
                'StaffXIX',
                'VoiceXIX',
                'StaffXX',
                'VoiceXX',
                'StaffXXI',
                'VoiceXXI',
                'StaffXXII',
                'VoiceXXII',
                'StaffXXIII',
                'VoiceXXIII',
                'StaffXXIV',
                'VoiceXXIV',
                'StaffXXV',
                'VoiceXXV',
                'StaffXXVI',
                'VoiceXXVI',
                'StaffXXVII',
                'VoiceXXVII',
                'StaffXXVIII',
                'VoiceXXVIII',
                'StaffXXIX',
                'VoiceXXIX',
                'StaffXXX',
                'VoiceXXX',
                'StaffXXXI',
                'VoiceXXXI',
                'StaffXXXII',
                'VoiceXXXII',
                'StaffXXXIII',
                'VoiceXXXIII',
                'StaffXXXIV',
                'VoiceXXXIV',
                'StaffXXXV',
                'VoiceXXXV',
                'StaffXXXVI',
                'VoiceXXXVI',
                'StaffXXXVII',
                'VoiceXXXVII',
                'StaffXXXVIII',
                'VoiceXXXVIII',
                'StaffXXXIX',
                'VoiceXXXIX',
                'StaffXL',
                'VoiceXL',
                'StaffXLI',
                'VoiceXLI',
                'StaffXLII',
                'VoiceXLII',
                'StaffXLIII',
                'VoiceXLIII',
                'StaffXLIV',
                'VoiceXLIV',
                'StaffXLV',
                'VoiceXLV',
                'StaffXLVI',
                'VoiceXLVI',
                'StaffXLVII',
                'VoiceXLVII',
                'StaffXLVIII',
                'VoiceXLVIII',
                'StaffXLIX',
                'VoiceXLIX',
                'StaffL',
                'VoiceL',
                'StaffLI',
                'VoiceLI',
                'StaffLII',
                'VoiceLII',
                'StaffLIII',
                'VoiceLIII',
                'StaffLIV',
                'VoiceLIV',
                'StaffLV',
                'VoiceLV',
                'StaffLVI',
                'VoiceLVI',
                'StaffLVII',
                'VoiceLVII',
                'StaffLVIII',
                'VoiceLVIII',
                'StaffLIX',
                'VoiceLIX',
                'StaffLX',
                'VoiceLX',
                'StaffLXI',
                'VoiceLXI',
                'StaffLXII',
                'VoiceLXII',
                'StaffLXIII',
                'VoiceLXIII',
                'StaffLXIV',
                'VoiceLXIV',
                ],
            ),
        ('duration', "0'24''"),
        ('first_measure_number', 113),
        ('last_measure_number', 128),
        (
            'persistent_indicators',
            abjad.OrderedDict(
                [
                    (
                        'Score',
                        [
                            abjad.Momento(
                                context='GlobalSkips',
                                prototype='abjad.MetronomeMark',
                                value='38-42',
                                ),
                            abjad.Momento(
                                context='GlobalSkips',
                                prototype='abjad.TimeSignature',
                                value='2/4',
                                ),
                            ],
                        ),
                    (
                        'StaffI',
                        [
                            abjad.Momento(
                                context='VoiceI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='1',
                                ),
                            ],
                        ),
                    (
                        'StaffII',
                        [
                            abjad.Momento(
                                context='VoiceII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='2',
                                ),
                            ],
                        ),
                    (
                        'StaffIII',
                        [
                            abjad.Momento(
                                context='VoiceIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='3',
                                ),
                            ],
                        ),
                    (
                        'StaffIV',
                        [
                            abjad.Momento(
                                context='VoiceIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceIV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceIV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='4',
                                ),
                            ],
                        ),
                    (
                        'StaffIX',
                        [
                            abjad.Momento(
                                context='VoiceIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceIX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceIX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='9',
                                ),
                            ],
                        ),
                    (
                        'StaffL',
                        [
                            abjad.Momento(
                                context='VoiceL',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceL',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceL',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='50',
                                ),
                            ],
                        ),
                    (
                        'StaffLI',
                        [
                            abjad.Momento(
                                context='VoiceLI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='51',
                                ),
                            ],
                        ),
                    (
                        'StaffLII',
                        [
                            abjad.Momento(
                                context='VoiceLII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='52',
                                ),
                            ],
                        ),
                    (
                        'StaffLIII',
                        [
                            abjad.Momento(
                                context='VoiceLIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='53',
                                ),
                            ],
                        ),
                    (
                        'StaffLIV',
                        [
                            abjad.Momento(
                                context='VoiceLIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLIV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLIV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='54',
                                ),
                            ],
                        ),
                    (
                        'StaffLIX',
                        [
                            abjad.Momento(
                                context='VoiceLIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLIX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLIX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='59',
                                ),
                            ],
                        ),
                    (
                        'StaffLV',
                        [
                            abjad.Momento(
                                context='VoiceLV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='55',
                                ),
                            ],
                        ),
                    (
                        'StaffLVI',
                        [
                            abjad.Momento(
                                context='VoiceLVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLVI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLVI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='56',
                                ),
                            ],
                        ),
                    (
                        'StaffLVII',
                        [
                            abjad.Momento(
                                context='VoiceLVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLVII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLVII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='57',
                                ),
                            ],
                        ),
                    (
                        'StaffLVIII',
                        [
                            abjad.Momento(
                                context='VoiceLVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLVIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLVIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='58',
                                ),
                            ],
                        ),
                    (
                        'StaffLX',
                        [
                            abjad.Momento(
                                context='VoiceLX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='60',
                                ),
                            ],
                        ),
                    (
                        'StaffLXI',
                        [
                            abjad.Momento(
                                context='VoiceLXI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLXI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLXI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='61',
                                ),
                            ],
                        ),
                    (
                        'StaffLXII',
                        [
                            abjad.Momento(
                                context='VoiceLXII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLXII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLXII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='62',
                                ),
                            ],
                        ),
                    (
                        'StaffLXIII',
                        [
                            abjad.Momento(
                                context='VoiceLXIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLXIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLXIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='63',
                                ),
                            ],
                        ),
                    (
                        'StaffLXIV',
                        [
                            abjad.Momento(
                                context='VoiceLXIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLXIV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceLXIV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='64',
                                ),
                            ],
                        ),
                    (
                        'StaffV',
                        [
                            abjad.Momento(
                                context='VoiceV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='5',
                                ),
                            ],
                        ),
                    (
                        'StaffVI',
                        [
                            abjad.Momento(
                                context='VoiceVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceVI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceVI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='6',
                                ),
                            ],
                        ),
                    (
                        'StaffVII',
                        [
                            abjad.Momento(
                                context='VoiceVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceVII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceVII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='7',
                                ),
                            ],
                        ),
                    (
                        'StaffVIII',
                        [
                            abjad.Momento(
                                context='VoiceVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceVIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceVIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='8',
                                ),
                            ],
                        ),
                    (
                        'StaffX',
                        [
                            abjad.Momento(
                                context='VoiceX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='10',
                                ),
                            ],
                        ),
                    (
                        'StaffXI',
                        [
                            abjad.Momento(
                                context='VoiceXI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='11',
                                ),
                            ],
                        ),
                    (
                        'StaffXII',
                        [
                            abjad.Momento(
                                context='VoiceXII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='12',
                                ),
                            ],
                        ),
                    (
                        'StaffXIII',
                        [
                            abjad.Momento(
                                context='VoiceXIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='13',
                                ),
                            ],
                        ),
                    (
                        'StaffXIV',
                        [
                            abjad.Momento(
                                context='VoiceXIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXIV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXIV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='14',
                                ),
                            ],
                        ),
                    (
                        'StaffXIX',
                        [
                            abjad.Momento(
                                context='VoiceXIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXIX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXIX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='19',
                                ),
                            ],
                        ),
                    (
                        'StaffXL',
                        [
                            abjad.Momento(
                                context='VoiceXL',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXL',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXL',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='40',
                                ),
                            ],
                        ),
                    (
                        'StaffXLI',
                        [
                            abjad.Momento(
                                context='VoiceXLI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='41',
                                ),
                            ],
                        ),
                    (
                        'StaffXLII',
                        [
                            abjad.Momento(
                                context='VoiceXLII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='42',
                                ),
                            ],
                        ),
                    (
                        'StaffXLIII',
                        [
                            abjad.Momento(
                                context='VoiceXLIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='43',
                                ),
                            ],
                        ),
                    (
                        'StaffXLIV',
                        [
                            abjad.Momento(
                                context='VoiceXLIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLIV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLIV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='44',
                                ),
                            ],
                        ),
                    (
                        'StaffXLIX',
                        [
                            abjad.Momento(
                                context='VoiceXLIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLIX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLIX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='49',
                                ),
                            ],
                        ),
                    (
                        'StaffXLV',
                        [
                            abjad.Momento(
                                context='VoiceXLV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='45',
                                ),
                            ],
                        ),
                    (
                        'StaffXLVI',
                        [
                            abjad.Momento(
                                context='VoiceXLVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLVI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLVI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='46',
                                ),
                            ],
                        ),
                    (
                        'StaffXLVII',
                        [
                            abjad.Momento(
                                context='VoiceXLVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLVII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLVII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='47',
                                ),
                            ],
                        ),
                    (
                        'StaffXLVIII',
                        [
                            abjad.Momento(
                                context='VoiceXLVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLVIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXLVIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='48',
                                ),
                            ],
                        ),
                    (
                        'StaffXV',
                        [
                            abjad.Momento(
                                context='VoiceXV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='15',
                                ),
                            ],
                        ),
                    (
                        'StaffXVI',
                        [
                            abjad.Momento(
                                context='VoiceXVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXVI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXVI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='16',
                                ),
                            ],
                        ),
                    (
                        'StaffXVII',
                        [
                            abjad.Momento(
                                context='VoiceXVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXVII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXVII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='17',
                                ),
                            ],
                        ),
                    (
                        'StaffXVIII',
                        [
                            abjad.Momento(
                                context='VoiceXVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXVIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXVIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='18',
                                ),
                            ],
                        ),
                    (
                        'StaffXX',
                        [
                            abjad.Momento(
                                context='VoiceXX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='20',
                                ),
                            ],
                        ),
                    (
                        'StaffXXI',
                        [
                            abjad.Momento(
                                context='VoiceXXI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='21',
                                ),
                            ],
                        ),
                    (
                        'StaffXXII',
                        [
                            abjad.Momento(
                                context='VoiceXXII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='22',
                                ),
                            ],
                        ),
                    (
                        'StaffXXIII',
                        [
                            abjad.Momento(
                                context='VoiceXXIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='23',
                                ),
                            ],
                        ),
                    (
                        'StaffXXIV',
                        [
                            abjad.Momento(
                                context='VoiceXXIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXIV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXIV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='24',
                                ),
                            ],
                        ),
                    (
                        'StaffXXIX',
                        [
                            abjad.Momento(
                                context='VoiceXXIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXIX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXIX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='29',
                                ),
                            ],
                        ),
                    (
                        'StaffXXV',
                        [
                            abjad.Momento(
                                context='VoiceXXV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='25',
                                ),
                            ],
                        ),
                    (
                        'StaffXXVI',
                        [
                            abjad.Momento(
                                context='VoiceXXVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXVI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXVI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='26',
                                ),
                            ],
                        ),
                    (
                        'StaffXXVII',
                        [
                            abjad.Momento(
                                context='VoiceXXVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXVII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXVII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='27',
                                ),
                            ],
                        ),
                    (
                        'StaffXXVIII',
                        [
                            abjad.Momento(
                                context='VoiceXXVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXVIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXVIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='28',
                                ),
                            ],
                        ),
                    (
                        'StaffXXX',
                        [
                            abjad.Momento(
                                context='VoiceXXX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='30',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXI',
                        [
                            abjad.Momento(
                                context='VoiceXXXI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='31',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXII',
                        [
                            abjad.Momento(
                                context='VoiceXXXII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='32',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXIII',
                        [
                            abjad.Momento(
                                context='VoiceXXXIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='33',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXIV',
                        [
                            abjad.Momento(
                                context='VoiceXXXIV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXIV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXIV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='34',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXIX',
                        [
                            abjad.Momento(
                                context='VoiceXXXIX',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXIX',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXIX',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='39',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXV',
                        [
                            abjad.Momento(
                                context='VoiceXXXV',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXV',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXV',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='35',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXVI',
                        [
                            abjad.Momento(
                                context='VoiceXXXVI',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXVI',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXVI',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='36',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXVII',
                        [
                            abjad.Momento(
                                context='VoiceXXXVII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXVII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXVII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='37',
                                ),
                            ],
                        ),
                    (
                        'StaffXXXVIII',
                        [
                            abjad.Momento(
                                context='VoiceXXXVIII',
                                prototype='abjad.Clef',
                                value='percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXVIII',
                                prototype='abjad.Instrument',
                                value='Percussion',
                                ),
                            abjad.Momento(
                                context='VoiceXXXVIII',
                                edition=abjad.Tag('-PARTS'),
                                prototype='abjad.MarginMarkup',
                                value='38',
                                ),
                            ],
                        ),
                    ]
                ),
            ),
        ('segment_name', 'G'),
        ('segment_number', 8),
        (
            'sounds_during_segment',
            abjad.OrderedDict(
                [
                    ('VoiceI', True),
                    ('VoiceII', True),
                    ('VoiceIII', True),
                    ('VoiceIV', True),
                    ('VoiceIX', True),
                    ('VoiceL', True),
                    ('VoiceLI', True),
                    ('VoiceLII', True),
                    ('VoiceLIII', True),
                    ('VoiceLIV', True),
                    ('VoiceLIX', True),
                    ('VoiceLV', True),
                    ('VoiceLVI', True),
                    ('VoiceLVII', True),
                    ('VoiceLVIII', True),
                    ('VoiceLX', True),
                    ('VoiceLXI', True),
                    ('VoiceLXII', True),
                    ('VoiceLXIII', True),
                    ('VoiceLXIV', True),
                    ('VoiceV', True),
                    ('VoiceVI', True),
                    ('VoiceVII', True),
                    ('VoiceVIII', True),
                    ('VoiceX', True),
                    ('VoiceXI', True),
                    ('VoiceXII', True),
                    ('VoiceXIII', True),
                    ('VoiceXIV', True),
                    ('VoiceXIX', True),
                    ('VoiceXL', True),
                    ('VoiceXLI', True),
                    ('VoiceXLII', True),
                    ('VoiceXLIII', True),
                    ('VoiceXLIV', True),
                    ('VoiceXLIX', True),
                    ('VoiceXLV', True),
                    ('VoiceXLVI', True),
                    ('VoiceXLVII', True),
                    ('VoiceXLVIII', True),
                    ('VoiceXV', True),
                    ('VoiceXVI', True),
                    ('VoiceXVII', True),
                    ('VoiceXVIII', True),
                    ('VoiceXX', True),
                    ('VoiceXXI', True),
                    ('VoiceXXII', True),
                    ('VoiceXXIII', True),
                    ('VoiceXXIV', True),
                    ('VoiceXXIX', True),
                    ('VoiceXXV', True),
                    ('VoiceXXVI', True),
                    ('VoiceXXVII', True),
                    ('VoiceXXVIII', True),
                    ('VoiceXXX', True),
                    ('VoiceXXXI', True),
                    ('VoiceXXXII', True),
                    ('VoiceXXXIII', True),
                    ('VoiceXXXIV', True),
                    ('VoiceXXXIX', True),
                    ('VoiceXXXV', True),
                    ('VoiceXXXVI', True),
                    ('VoiceXXXVII', True),
                    ('VoiceXXXVIII', True),
                    ]
                ),
            ),
        ('start_clock_time', "2'48''"),
        ('stop_clock_time', "3'12''"),
        (
            'time_signatures',
            [
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                '2/4',
                ],
            ),
        ]
    )
